using AutoGenerateDDDProjectForNetCore.models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.XPath;

namespace AutoGenerateDDDProjectForNetCore
{
    public static class XMLSettings
    {
        public const string VERSION = "RELEASE1";
        public static bool ShowToU { get; set; } = false;
        public static string ProjectName { get; set; } = "";
        public static string DatabaseName { get; set; } = "";
        public static string GitUri { get; set; } = "";
        public static string SQLServerName { get; set; } = ".\\SQLEXPRESS";
        public static string SQLUsername { get; set; } = "sa";
        public static string SQLPassword { get; set; } = "123@bcd";
        public static string TypeSQL { get; set; } = "MSSQL";
        public static List<EntityModel> Entities { get; set; } = new List<EntityModel>();

        private static string _settingsFilePath = Path.Combine(Application.StartupPath, "settings.xml");
        public static bool WriteDefaultSettings()
        {
            try
            {
                if (!File.Exists(_settingsFilePath))
                {
                    XmlDocument doc = new XmlDocument();
                    XmlNode root = doc.CreateElement("settings");
                    doc.AppendChild(root);

                    root.AppendChild(doc.CreateElement("SQLServerName")).InnerText = SQLServerName;
                    root.AppendChild(doc.CreateElement("SQLUsername")).InnerText = SQLUsername;
                    root.AppendChild(doc.CreateElement("SQLPassword")).InnerText = SQLPassword;
                    root.AppendChild(doc.CreateElement("TypeSQL")).InnerText = TypeSQL;
                    root.AppendChild(doc.CreateElement("ShowToU")).InnerText = ShowToU.ToString();

                    doc.Save(_settingsFilePath);
                }
                return true;
            }
            catch
            {
                return false;
            }
        }
        public static string ReadValue(string pstrValueToRead)
        {
            try
            {
                XPathDocument doc = new XPathDocument(_settingsFilePath);
                XPathNavigator nav = doc.CreateNavigator();
                var expr = nav.Compile(@"/settings/" + pstrValueToRead);
                XPathNodeIterator iterator = nav.Select(expr);
                while (iterator.MoveNext())
                {
                    return iterator.Current.Value;
                }

                return string.Empty;
            }
            catch
            {
                return string.Empty;
            }
        }

        public static bool WriteValue(string pstrValueToRead, string pstrValueToWrite)
        {
            try
            {
                XmlDocument doc = new XmlDocument();
                using (var reader = new XmlTextReader(_settingsFilePath))
                {
                    doc.Load(reader);
                }

                XmlElement root = doc.DocumentElement;
                var oldNode = root.SelectSingleNode(@"/settings/" + pstrValueToRead);
                if (oldNode == null) // create if not exist
                {
                    oldNode = doc.SelectSingleNode("settings");
                    oldNode.AppendChild(doc.CreateElement(pstrValueToRead)).InnerText = pstrValueToWrite;
                    doc.Save(_settingsFilePath);
                    return true;
                }
                oldNode.InnerText = pstrValueToWrite;
                doc.Save(_settingsFilePath);
                return true;
            }
            catch
            {
                return false;
            }
        }
    }
}
