namespace AutoGenerateDDDProjectForNetCore.forms
{
    partial class frmSelectEntity
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.tvColumn = new System.Windows.Forms.TreeView();
            this.tvDependency = new System.Windows.Forms.TreeView();
            this.btnOK = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // tvColumn
            // 
            this.tvColumn.CheckBoxes = true;
            this.tvColumn.Location = new System.Drawing.Point(12, 12);
            this.tvColumn.Name = "tvColumn";
            this.tvColumn.Size = new System.Drawing.Size(334, 577);
            this.tvColumn.TabIndex = 0;
            this.tvColumn.NodeMouseClick += new System.Windows.Forms.TreeNodeMouseClickEventHandler(this.tvColumn_NodeMouseClick);
            // 
            // tvDependency
            // 
            this.tvDependency.CheckBoxes = true;
            this.tvDependency.Location = new System.Drawing.Point(352, 12);
            this.tvDependency.Name = "tvDependency";
            this.tvDependency.Size = new System.Drawing.Size(345, 577);
            this.tvDependency.TabIndex = 1;
            // 
            // btnOK
            // 
            this.btnOK.Location = new System.Drawing.Point(622, 595);
            this.btnOK.Name = "btnOK";
            this.btnOK.Size = new System.Drawing.Size(75, 23);
            this.btnOK.TabIndex = 2;
            this.btnOK.Text = "OK";
            this.btnOK.UseVisualStyleBackColor = true;
            this.btnOK.Click += new System.EventHandler(this.btnOK_Click);
            // 
            // frmSelectEntity
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(709, 626);
            this.Controls.Add(this.btnOK);
            this.Controls.Add(this.tvDependency);
            this.Controls.Add(this.tvColumn);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmSelectEntity";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Select Entity for domain";
            this.Load += new System.EventHandler(this.frmSelectEntity_Load);
            this.ResumeLayout(false);

        }

        #endregion

        private TreeView tvColumn;
        private TreeView tvDependency;
        private Button btnOK;
    }
}