using AutoGenerateDDDProjectForNetCore.services;

namespace AutoGenerateDDDProjectForNetCore.models
{
    public class EntityModel
    {
        public string Entity { get; set; }
        public List<string> Dependency { get; set; }
        public bool IsChecked { get; set; }
        public ColumnModel[] Columns { get; set; }
    }
}